ifdef CONFIG_CURL_LIBRARY

COMPONENT_SRCDIRS:=curl/lib curl/lib/vauth curllib/vtls
COMPONENT_PRIV_INCLUDEDIRS:=curl/lib curl/include
CFLAGS+=-DHAVE_CONFIG_H -DBUILDING_LIBCURL

else
COMPONENT_SRCDIRS:=
COMPONENT_PRIV_INCLUDEDIRS:=
CFLAGS+=
endif
